name: view-fusion
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - anyio=4.2.0=py311hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - babel=2.11.0=py311hca03da5_0
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h313beb8_0
  - braceexpand=0.1.5=py_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py311h313beb8_7
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.12.12=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2024.2.2=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_0
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - comm=0.1.2=py311hca03da5_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - eigen=3.4.0=h48ca7d4_0
  - einops=0.7.0=pyhd8ed1ab_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h313beb8_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.13.1=py311hca03da5_0
  - fontconfig=2.14.1=hee714a5_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py311hca03da5_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h05c076b_3
  - icu=68.1=hc377ac9_0
  - idna=3.4=py311hca03da5_0
  - imagecodecs=2023.1.23=py311h5e7c512_0
  - imageio=2.33.1=py311hca03da5_0
  - ipykernel=6.28.0=py311hca03da5_0
  - ipython=8.20.0=py311hca03da5_0
  - ipywidgets=8.0.4=py311hca03da5_0
  - jedi=0.18.1=py311hca03da5_1
  - jinja2=3.1.3=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter=1.0.0=py311hca03da5_9
  - jupyter-lsp=2.2.0=py311hca03da5_0
  - jupyter_client=8.6.0=py311hca03da5_0
  - jupyter_console=6.6.3=py311hca03da5_0
  - jupyter_core=5.5.0=py311hca03da5_0
  - jupyter_events=0.8.0=py311hca03da5_0
  - jupyter_server=2.10.0=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab=4.0.11=py311hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311hca03da5_0
  - jupyterlab_widgets=3.0.9=py311hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lazy_loader=0.3=py311hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libavif=0.11.1=h80987f9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.5.0=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h1a28f6b_2
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=h02f6b3c_2
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lpips=0.1.3=pyhd8ed1ab_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib-base=3.8.0=py311h7aedaa7_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mistune=2.0.4=py311hca03da5_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py311hca03da5_0
  - nbconvert=7.10.0=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=py311hca03da5_0
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.1=py311hca03da5_0
  - notebook=7.0.8=py311hca03da5_0
  - notebook-shim=0.2.3=py311hca03da5_0
  - numpy=1.26.3=py311he598dae_0
  - numpy-base=1.26.3=py311hfbfe69c_0
  - opencv=4.6.0=py311hbae66a1_5
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.13=h1a28f6b_0
  - overrides=7.4.0=py311hca03da5_0
  - packaging=23.1=py311hca03da5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre2=10.42=hb066dcc_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.2.0=py311h80987f9_0
  - pip=23.3.1=py311hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py311hca03da5_0
  - ply=3.11=py311hca03da5_0
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.43=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=3.20.3=py311h313beb8_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hca03da5_1
  - pyparsing=3.0.9=py311hca03da5_0
  - pyqt=5.15.10=py311h313beb8_0
  - pyqt5-sip=12.13.0=py311h80987f9_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.7=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - pytorch=2.2.0=py3.11_0
  - pytorch-msssim=1.0.0=pyhd8ed1ab_0
  - pytz=2023.3.post1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=25.1.2=py311h313beb8_0
  - qt-main=5.15.2=h9b4df51_9
  - qt-webengine=5.15.9=h2903aaf_7
  - qtconsole=5.5.0=py311hca03da5_0
  - qtpy=2.4.1=py311hca03da5_0
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py311hca03da5_0
  - requests=2.31.0=py311hca03da5_1
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rpds-py=0.10.6=py311hf0e4da2_0
  - scikit-image=0.22.0=py311h7aedaa7_0
  - scipy=1.11.4=py311hc76d9b0_0
  - send2trash=1.8.2=py311hca03da5_0
  - sentry-sdk=1.9.0=py311hca03da5_0
  - setproctitle=1.2.2=py311h80987f9_0
  - setuptools=68.2.2=py311hca03da5_0
  - sip=6.7.12=py311h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h313beb8_1
  - sniffio=1.3.0=py311hca03da5_0
  - soupsieve=2.5=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py311hca03da5_0
  - terminado=0.17.1=py311hca03da5_0
  - tifffile=2023.4.12=py311hca03da5_0
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchaudio=2.2.0=py311_cpu
  - torchvision=0.17.0=py311_cpu
  - tornado=6.3.3=py311h80987f9_0
  - tqdm=4.65.0=py311hb6e6a13_0
  - traitlets=5.7.1=py311hca03da5_0
  - typing-extensions=4.9.0=py311hca03da5_1
  - typing_extensions=4.9.0=py311hca03da5_1
  - tzdata=2023d=h04d1e81_0
  - urllib3=2.1.0=py311hca03da5_1
  - wandb=0.16.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webdataset=0.2.86=pyhd8ed1ab_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=0.58.0=py311hca03da5_4
  - wheel=0.41.2=py311hca03da5_0
  - widgetsnbextension=4.0.5=py311hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.5=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zfp=1.0.0=h313beb8_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
prefix: /Users/spieglb1/miniconda3/envs/view-fusion
