name: view-fusion
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.3=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - python=3.11.7=h955ad1f_0
  - pytorch=2.2.0=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.2.0=py311
  - typing_extensions=4.9.0=py311h06a4308_1
  - tzdata=2023d=h04d1e81_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - appdirs==1.4.4
    - braceexpand==0.1.7
    - certifi==2024.2.2
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - filelock==3.13.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - gmpy2==2.1.2
    - idna==3.6
    - imageio==2.33.1
    - jinja2==3.1.3
    - markupsafe==2.1.3
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.26.3
    - pillow==10.2.0
    - pip==23.3.1
    - protobuf==4.25.3
    - psutil==5.9.8
    - pytorch-msssim==1.0.0
    - pyyaml==6.0.1
    - requests==2.31.0
    - sentry-sdk==1.40.5
    - setproctitle==1.3.3
    - setuptools==68.2.2
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.12
    - torch==2.2.0
    - torchaudio==2.2.0
    - torchvision==0.17.0
    - tqdm==4.65.0
    - triton==2.2.0
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - wandb==0.16.3
    - webdataset==0.2.86
    - wheel==0.41.2
prefix: /scratch/work/spieglb1/.conda_envs/view-fusion
